const COLOR_OPTIONS = [
  {
    name: "Натуральний віск",
    color: "#F1A213",
    select_saturation: false,
  },
  {
    name: "Айворі",
    color: "#F1A213",
    select_saturation: true,
  },
  {
    name: "Зелений",
    color: "#00ff00",
    select_saturation: true,
  },
  {
    name: "Темний шоколад",
    color: "#00ff00",
    select_saturation: true,
  },
  {
    name: "Інший колір",
    color: "#00ff00",
    select_saturation: true,
  },
];
const SATURATION = [
  {
    name: "light",
    price: 10,
  },
  {
    name: "medium",
    price: 15,
  },
  {
    name: "hue",
    price: 20,
  },
];

const CATALOG = [
  {
    id: "003",
    img: [
      "../bees-candles/images/product-img/christmas-tree-orange.jpg",
      "../bees-candles/images/product-img/christmas-tree-green.jpg",
      "../bees-candles/images/product-img/christmas-tree-green-in-snow.jpg",
      "../bees-candles/images/product-img/christmas-tree-green+blue-beads.jpg",
    ],
    name: "Свічка Ялинка",
    time: "7-8",
    mass: 60,
    height: 10,
    diameter: 0,
    select_color: true,
    price: 50,
  },
  {
    id: "002",
    img: [
      "../bees-candles/images/product-img/sheep-natural-wax-front-view.jpg",
      "../bees-candles/images/product-img/sheep-natural-wax-left-view.jpg",
      "../bees-candles/images/product-img/sheep-white-right-view.jpg",
      "../bees-candles/images/product-img/sheep-natural-wax-back-view.jpg",
    ],
    name: "Свічка Ягнятко",
    time: "7-8",
    mass: 100,
    height: 10,
    diameter: 0,
    select_color: true,
    price: 80,
  },
  {
    id: "001",
    img: [
      "../bees-candles/images/product-img/bee-on-honeycombs.jpg",
      "../bees-candles/images/product-img/bee-on-honeycombs.jpg",
      "../bees-candles/images/product-img/bee-on-honeycombs.jpg",
    ],
    name: "Свічка Бджілка",
    time: "~3",
    mass: 40,
    height: 2,
    diameter: 0,
    select_color: true,
    price: 30,
  },
  {
    id: "004",
    img: [
      "../bees-candles/images/product-img/beehive.jpg",
      "../bees-candles/images/product-img/beehive-v2.jpg",
      "../bees-candles/images/product-img/beehive-trio.jpg",
    ],
    name: "Свічка Бджолиний будиночок",
    time: "~5",
    mass: 60,
    height: 9,
    diameter: 0,
    select_color: true,
    price: 50,
  },
  {
    id: "005",
    img: [
      "../bees-candles/images/product-img/luck-bird-front-view.jpg",
      "../bees-candles/images/product-img/luck-bird-left-view.jpg",
      "../bees-candles/images/product-img/luck-bird-back-view.jpg",
      "../bees-candles/images/product-img/luck-bird-right-view.jpg",
    ],
    name: "Свічка Пташка Люк",
    time: "",
    mass: 60,
    height: 10,
    diameter: 0,
    select_color: true,
    price: 70,
  },
  {
    id: "006",
    img: [
      "../bees-candles/images/product-img/snowman-front-view.jpg",
      "../bees-candles/images/product-img/snowman-left-view.jpg",
      "../bees-candles/images/product-img/snowman-back-view.jpg",
      "../bees-candles/images/product-img/snowman-right-view.jpg",
    ],
    name: "Свічка Сніговик",
    time: "~7",
    mass: 60,
    height: 10,
    diameter: 0,
    select_color: true,
    price: 60,
  },
  {
    id: "007",
    img: [
      "../bees-candles/images/product-img/2.jpg",
      "../bees-candles/images/product-img/wax-candle.jpg",
      "../bees-candles/images/product-img/wax-candle.jpg",
    ],
    name: "Свічка з вощини товста",
    time: "~4",
    mass: 60,
    height: 12,
    diameter: 4.5,
    select_color: false,
    price: 70,
  },
  {
    id: "008",
    img: [
      "../bees-candles/images/product-img/wax-candle.jpg",
      "../bees-candles/images/product-img/wax-candle.jpg",
      "../bees-candles/images/product-img/wax-candle.jpg",
    ],
    name: "Свічка з вощини тонка",
    time: "~4",
    mass: 60,
    height: 12,
    diameter: 2.5,
    select_color: false,
    price: 35,
  },
  {
    id: "009",
    img: [
      "../bees-candles/images/product-img/rick-bird-fromt-view.jpg",
      "../bees-candles/images/product-img/rick-bird-left-view.jpg",
      "../bees-candles/images/product-img/rick-bird-back- view.jpg",
      "../bees-candles/images/product-img/rick-bird-right- view.jpg",
    ],
    name: "Свічка Пташка Рік",
    time: "",
    mass: 60,
    height: 10,
    diameter: 0,
    select_color: true,
    price: 80,
  },
  {
    id: "010",
    img: [
      "../bees-candles/images/product-img/chick-bird-front-view.jpg",
      "../bees-candles/images/product-img/chick-bird-left-view.jpg",
      "../bees-candles/images/product-img/chick-bird-back-view.jpg",
      "../bees-candles/images/product-img/chick-bird-right-view.jpg",
    ],
    name: "Свічка Пташка Чік",
    time: "~7",
    mass: 60,
    height: 10,
    diameter: 4,
    select_color: true,
    price: 80,
  },
  {
    id: "011",
    img: [
      "../bees-candles/images/product-img/owl-natural-wax-front-veiw.jpg",
      "../bees-candles/images/product-img/owl-natural-wax-left-veiw.jpg",
      "../bees-candles/images/product-img/owl-natural-wax-back-veiw.jpg",
      "../bees-candles/images/product-img/owl-natural-wax-right-veiw.jpg",
    ],
    name: "Свічка Совушка",
    time: "~2",
    mass: 60,
    height: 4.5,
    diameter: 4,
    select_color: true,
    price: 25,
  },
];
