const CATALOG = [
  {
    id: 001,
    img: "../bees-candles/images/product-img/spruce.jpg",
    name: "Свічка Ялинка",
    time: "",
    weight: 60,
    price: 30,
  },
  {
    id: 002,
    img: "../bees-candles/images/product-img/sheep.jpg",
    name: "Свічка Овечка",
    time: "",
    weight: 60,
    price: 0,
  },
  {
    id: 003,
    img: "../bees-candles/images/product-img/1.jpg",
    name: "Свічка Бджілка",
    time: "",
    weight: 60,
    price: 0,
  },
  {
    id: 004,
    img: "../bees-candles/images/product-img/2.jpg",
    name: "Свічка Хатинка",
    time: "",
    weight: 60,
    price: 0,
  },
  {
    id: 005,
    img: "../bees-candles/images/product-img/bird.jpg",
    name: "Свічка Пташка",
    time: "",
    weight: 60,
    price: 0,
  },
  {
    id: 006,
    img: "../bees-candles/images/product-img/snow-men.jpg",
    name: "Свічка Сніговик",
    time: "",
    weight: 60,
    price: 0,
  },
];
